GET http://localhost:5007/employees

//Pra adicionar outro request precisa do '###'
###
GET http://localhost:5007/employees/7

###

POST http://localhost:5007/employees
Content-Type: application/json

{
    "name": "Cleyton",
    "role": "Funcionário"
}

###

PUT http://localhost:5007/employees/1
Content-Type: application/json

{
    "name": "José",
    "role": "Gerente"
}

###

DELETE http://localhost:5007/employees/4
